color0 #131313
color1 #ffb4ab
color2 #8dcdff
color3 #b7c9d9
color4 #cfc0e8
color5 #8dcdff
color6 #b7c9d9
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #8dcdff
color11 #b7c9d9
color12 #cfc0e8
color13 #8dcdff
color14 #b7c9d9
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #8dcdff
inactive_border_color #474747
url_color             #8dcdff
