cursor #e3e2e2
cursor_text_color #c7c6c7

foreground            #e3e2e2
background            #121314
selection_foreground  #2a3235
selection_background  #c0c8cc
url_color             #bac9d1

color0   #121314
color1   #f06c96
color2   #68d174
color3   #fff672
color4   #acbdc6
color5   #4d5960
color6   #bac9d1
color7   #ced6db
color8   #7d8487
color9   #ff9fbd
color10  #a3faad
color11  #fff9a5
color12  #d0dee5
color13  #ebf8ff
color14  #f2faff
color15  #f8fcff
