# Handle "copy:text" links by copying to system clipboard
protocol copy
action launch --type=background sh -c "echo -n '$URL' | cut -d: -f2- | wl-copy"
action launch --type=background notify-send "Kitty" "Copied to clipboard"
